apiVersion: v2
name: qualytics
description: A Helm chart for deploying Qualytics on Kubernetes
type: application
version: 2023.06.20
appVersion: "2023.06.20"
dependencies:
- name: spark-operator
  version: "1.x"
  repository: "https://googlecloudplatform.github.io/spark-on-k8s-operator"
- name: ingress-nginx
  version: "4.x"
  repository: "https://kubernetes.github.io/ingress-nginx"
- name: cert-manager
  version: "1.x"
  repository: "https://charts.jetstack.io"