######------------------------------------------------------------
# Qualytics default values
######------------------------------------------------------------

#--------------------------------------------------------------------------------
# Dependencies
#--------------------------------------------------------------------------------
spark-operator:
  webhook:
    enable: true
    port: 443
  nodeSelector:
    appNodes: "true"

ingress-nginx:
  controller:
    nodeSelector:
      appNodes: "true"
    admissionWebhooks:
      enabled: true
      timeoutSeconds: 30
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-type: nlb

cert-manager:
  installCRDs: "true"
  nodeSelector:
    appNodes: "true"

#--------------------------------------------------------------------------------
# Secrets
#--------------------------------------------------------------------------------

# The following secrets are required
secrets:
  auth0:
    auth0_domain: qualytics-dev.us.auth0.com
    auth0_audience: develop-api
    auth0_organization: org_develop
    auth0_spa_client_id: spa_client_id
    auth0_client_id: m2m_client_id
    auth0_client_secret: m2m_client_secret
    auth0_user_client_id: m2m_user_client_id
    auth0_user_client_secret: m2m_user_client_secret
  postgres:
    connection_url: postgres:postgres@postgres:5432/surveillence_hub
    secrets_passphrase: ChangeMe!
  smtp:
    smtp_sender_user: smtp_user
    smtp_sender_password: smtp_password
  rabbitmq:
    rabbitmq_password: ChangeMe!

#--------------------------------------------------------------------------------
# Global values
#--------------------------------------------------------------------------------

# Keep this for dns records and other specifics that are used across the entire app
global:
  platform: "local"
  tenant: "develop"
  dnsRecord: "{{ .Values.global.tenant }}.qualytics.io"
  imageUrls:
    firewallImageUrl: "artifactory.qualytics.io:443/docker/firewall-prod"
    hubImageUrl: "artifactory.qualytics.io:443/docker/hub-prod"
    frontendImageUrl: "artifactory.qualytics.io:443/docker/frontend-prod"

#--------------------------------------------------------------------------------
# Firewall configuration
#--------------------------------------------------------------------------------
firewallImage:
  image:
    firewallImageTag: "latest"

firewall:
  sparkVersion: "3.3.2"
  eventLog:
    enable: "false"
  useCache: "true"
  numRepartition: 0
  partitionSize: 10000000
  threadPoolParallelism: -1
  driver:
    cores: 1
    coreLimit: "1500m"
    memory: "2000m"
  dynamicAllocation:
    enabled: false
    initialExecutors: 0
    minExecutors: 0
    maxExecutors: 10
  executor:
    ## Note that if dynamic allocation is enabled, the number of executors to request initially is set to the biggest
    # of .spec.dynamicAllocation.initialExecutors and .spec.executor.instances if both are set.
    instances: 1
    cores: 1
    coreLimit: "1500m"
    memory: "2000m"

#--------------------------------------------------------------------------------
# Hub configuration
#--------------------------------------------------------------------------------
hubImage:
  image:
    hubImageTag: "latest"

hub:
  replicas: 1
  ingress:
    path: "/api/?(.*)"
    servicePort: "8000"
  resources:
    memory: "1Gi"
    cpu: "1000m"

hubCmd:
  resources:
    memory: "256Mi"
    cpu: "200m"

hubUserKeys:
  enabled: true

#--------------------------------------------------------------------------------
# Frontend configuration
#--------------------------------------------------------------------------------
frontendImage:
  image:
    frontendImageTag: "latest"

frontend:
  replicas: 1
  ingress:
    path: "/?(.*)"
    servicePort: "8080"
  resources:
    memory: "256Mi"
    cpu: "200m"

#--------------------------------------------------------------------------------
# Postgres
#--------------------------------------------------------------------------------
# Set values for cluster install of Postgres
postgres:
  enabled: true
  pvc:
    storageSize: "10Gi"
    backupVolumeStorageSize: "5Gi"
  image:
    version: "14"
  resources:
    memory: "4Gi"
    cpu: "1000m"

#--------------------------------------------------------------------------------
# Ingress Nginx & Cert-manager
#--------------------------------------------------------------------------------
ingress:
  enabled: false
  certificates:
    registeredEmail: "devops@qualytics.co"
