######------------------------------------------------------------
# Qualytics default values
######------------------------------------------------------------

#--------------------------------------------------------------------------------
# Dependencies
#--------------------------------------------------------------------------------
sparkoperator:
  enabled: true
  webhook:
    enable: true
    port: 443
    initAnnotations:
      "helm.sh/hook": pre-install
      "helm.sh/hook-weight": "50"
    cleanupAnnotations:
      "helm.sh/hook": pre-delete
      "helm.sh/hook-delete-policy": hook-succeeded
  # nodeSelector:
  #   appNodes: "true"
  # tolerations:
  #   - key: appNodes
  #     operator: Equal
  #     value: "true"
  #     effect: NoSchedule

nginx:
  enabled: false
  controller:
    # nodeSelector:
    #   appNodes: "true"
    # tolerations:
    #   - key: appNodes
    #     operator: Equal
    #     value: "true"
    #     effect: NoSchedule
    admissionWebhooks:
      enabled: true
      timeoutSeconds: 30
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local

certmanager:
  enabled: false
  registeredEmail: "devops@qualytics.co"
  installCRDs: "true"
  # nodeSelector:
  #   appNodes: "true"
  # tolerations:
  #   - key: appNodes
  #     operator: Equal
  #     value: "true"
  #     effect: NoSchedule

#--------------------------------------------------------------------------------
# App Ingresses
#--------------------------------------------------------------------------------
ingress:
  enabled: false

#--------------------------------------------------------------------------------
# Global values
#--------------------------------------------------------------------------------

# Keep this for dns records and other specifics that are used across the entire app
global:
  platform: "local"
  dnsRecord: "changeme.qualytics.io"
  imageUrls:
    firewallImageUrl: "qualyticsai/firewall-prod"
    hubImageUrl: "qualyticsai/hub-prod"
    frontendImageUrl: "qualyticsai/frontend-prod"

# Storage classes
storageClass:
  create: false
  name: ""

# Node scheduling
tolerations:
  enabled: false
selectors:
  enabled: false

# App image tags
firewallImage:
  image:
    firewallImageTag: "latest"
hubImage:
  image:
    hubImageTag: "latest"
frontendImage:
  image:
    frontendImageTag: "latest"

#--------------------------------------------------------------------------------
# Secrets
#--------------------------------------------------------------------------------
secrets:
  auth0: # required for authType AUTH0 (the default)
    auth0_domain: auth.qualytics.io
    auth0_audience: changeme-api
    auth0_organization: org_changeme
    auth0_spa_client_id: spa_client_id
  oidc: # required for authType OIDC
    oidc_scopes: oidc_scopes
    oidc_authorization_endpoint: oidc_authorization_endpoint
    oidc_token_endpoint: oidc_token_endpoint
    oidc_userinfo_endpoint: oidc_userinfo_endpoint
    oidc_client_id: oidc_client_id
    oidc_client_secret: oidc_client_secret
    oidc_user_id_key: oidc_user_id_key
    oidc_user_email_key: oidc_user_email_key
    oidc_user_name_key: oidc_user_name_key
    oidc_user_fname_key: oidc_user_fname_key
    oidc_user_lname_key: oidc_user_lname_key
    oidc_user_picture_key: oidc_user_picture_key
    oidc_user_provider_key: oidc_user_provider_key
    oidc_allow_insecure_transport: false
  auth:
    jwt_signing_secret: ChangeMe!
  postgres:
    host: postgres
    port: 5432
    database: surveillance_hub
    username: postgres
    password: postgres
    secrets_passphrase: ChangeMe!
  smtp:
    smtp_sender_user: smtp_user
    smtp_sender_password: smtp_password
  rabbitmq:
    rabbitmq_password: ChangeMe!

#--------------------------------------------------------------------------------
# Firewall configuration
#--------------------------------------------------------------------------------
firewall:
  sparkVersion: "3.5.1"
  eventLog: false
  rabbitmqPoolChannels: true
  useVolumes: false
  threadPoolParallelism: -1
  maxExecutors: 1
  numCoresPerExecutor: 1
  maxMemoryPerExecutor: 10
  libpostalDataPath: "/opt/libpostal"
  driver:
    cores: 1
    coreLimit: "1500m"
    memory: "2000m"
  dynamicAllocation:
    enabled: false
    initialExecutors: 0
    minExecutors: 0
    maxExecutors: 1
  executor:
    ## Note that if dynamic allocation is enabled, the number of executors to request initially is set to the biggest
    # of .spec.dynamicAllocation.initialExecutors and .spec.executor.instances if both are set.
    instances: 1
    cores: 1
    coreLimit: "1500m"
    memory: "2000m"

#--------------------------------------------------------------------------------
# Hub configuration
#--------------------------------------------------------------------------------
hub:
  replicas: 1
  authType: "AUTH0"
  ingress:
    path: "/api/?(.*)"
    servicePort: "8000"
  resources:
    memory: "1Gi"
    cpu: "1000m"
  smtp:
    enabled: false
    server: "email-smtp.us-east-1.amazonaws.com"
    sender: "no-reply@qualytics.co"
    port: "465"
  egress:
    verifyTLSCertificates: true # Controls certificate validation for all requests, httpx, and smtp_ssl sessions

hubCmd:
  resources:
    memory: "256Mi"
    cpu: "200m"

#--------------------------------------------------------------------------------
# Frontend configuration
#--------------------------------------------------------------------------------
frontend:
  replicas: 1
  ingress:
    path: "/?(.*)"
    servicePort: "8080"
  resources:
    memory: "256Mi"
    cpu: "200m"

#--------------------------------------------------------------------------------
# Postgres
#--------------------------------------------------------------------------------
# Set values for cluster install of Postgres
postgres:
  enabled: true
  pvc:
    storageSize: "10Gi"
    backupVolumeStorageSize: "5Gi"
  image:
    imageUrl: "postgres"
    imageTag: "16"
  resources:
    memory: "4Gi"
    cpu: "1000m"

#--------------------------------------------------------------------------------
# RabbitMQ
#--------------------------------------------------------------------------------
rabbitmq:
  pvc:
    storageSize: "10Gi"
  image:
    imageUrl: "rabbitmq"
    imageTag: "3.13-management"
  resources:
    memory: "1Gi"
    cpu: "1000m"

#--------------------------------------------------------------------------------
# Busybox
#--------------------------------------------------------------------------------
busybox:
  image:
    imageUrl: "busybox"
    imageTag: "latest"
