######------------------------------------------------------------
# Qualytics default values
######------------------------------------------------------------

#--------------------------------------------------------------------------------
# Dependencies
#--------------------------------------------------------------------------------
spark-operator:
  enabled: true
  webhook:
    enable: true
    port: 443
    initAnnotations:
      "helm.sh/hook": pre-install
      "helm.sh/hook-weight": "50"
    cleanupAnnotations:
      "helm.sh/hook": pre-delete
      "helm.sh/hook-delete-policy": hook-succeeded
  nodeSelector:
    appNodes: "true"
  # tolerations:
  #   - key: appNodes
  #     operator: Equal
  #     value: "true"
  #     effect: NoSchedule

ingress-nginx:
  enabled: false
  controller:
    nodeSelector:
      appNodes: "true"
    # tolerations:
    #   - key: appNodes
    #     operator: Equal
    #     value: "true"
    #     effect: NoSchedule
    admissionWebhooks:
      enabled: true
      timeoutSeconds: 30
    config:
      allow-snippet-annotations: "true"
      hsts-max-age: "31536000"
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      # annotations:
      #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      #   service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      #   service.beta.kubernetes.io/aws-load-balancer-type: nlb

cert-manager:
  enabled: false
  installCRDs: "true"
  nodeSelector:
    appNodes: "true"
  # tolerations:
  #   - key: appNodes
  #     operator: Equal
  #     value: "true"
  #     effect: NoSchedule

#--------------------------------------------------------------------------------
# Ingress Nginx & Cert-manager
#--------------------------------------------------------------------------------
ingress:
  enabled: false
  cors: false
  certificates:
    registeredEmail: "devops@qualytics.co"

#--------------------------------------------------------------------------------
# Global values
#--------------------------------------------------------------------------------

# Keep this for dns records and other specifics that are used across the entire app
global:
  platform: "aws"
  dnsRecord: "changeme.qualytics.io"
  imageUrls:
    firewallImageUrl: "artifactory.qualytics.io/docker/firewall-prod"
    hubImageUrl: "artifactory.qualytics.io/docker/hub-prod"
    frontendImageUrl: "artifactory.qualytics.io/docker/frontend-prod"

# Storage classes
storageClass:
  create: false
  name: ""

# Node scheduling
tolerations:
  enabled: false
selectors:
  enabled: true

# App image tags
firewallImage:
  image:
    firewallImageTag: "20231013-e6417cc"
hubImage:
  image:
    hubImageTag: "20231013-c66630a"
frontendImage:
  image:
    frontendImageTag: "20231013-6833a42"

# The following secrets are required
secrets:
  auth0:
    auth0_domain: auth.qualytics.io
    auth0_audience: changeme-api
    auth0_organization: org_changeme
    auth0_spa_client_id: spa_client_id
    auth0_client_id: m2m_client_id
    auth0_client_secret: m2m_client_secret
    auth0_user_client_id: m2m_user_client_id
    auth0_user_client_secret: m2m_user_client_secret
  postgres:
    connection_url: postgres:postgres@postgres:5432/surveillence_hub
    secrets_passphrase: ChangeMe!
  smtp:
    smtp_sender_user: smtp_user
    smtp_sender_password: smtp_password
  rabbitmq:
    rabbitmq_password: ChangeMe!

#--------------------------------------------------------------------------------
# Firewall configuration
#--------------------------------------------------------------------------------
firewall:
  sparkVersion: "3.4.1"
  eventLog: "false"
  useCache: "true"
  useVolumes: true
  threadPoolParallelism: -1
  maxExecutors: 20
  numCoresPerExecutor: 7
  maxMemoryPerExecutor: 56000
  driver:
    cores: 7
    coreLimit: "7800m"
    memory: "56000m"
  dynamicAllocation:
    enabled: true
    initialExecutors: 0
    minExecutors: 0
    maxExecutors: 20
  executor:
    ## Note that if dynamic allocation is enabled, the number of executors to request initially is set to the biggest
    # of .spec.dynamicAllocation.initialExecutors and .spec.executor.instances if both are set.
    instances: 1
    cores: 7
    coreLimit: "7800m"
    memory: "56000m"

#--------------------------------------------------------------------------------
# Hub configuration
#--------------------------------------------------------------------------------
hub:
  replicas: 3
  ingress:
    path: "/api/?(.*)"
    servicePort: "8000"
  resources:
    memory: "2Gi"
    cpu: "500m"
  smtp:
    enabled: true
    server: "email-smtp.us-east-1.amazonaws.com"
    sender: "no-reply@qualytics.co"
    port: "465"

hubCmd:
  resources:
    memory: "1Gi"
    cpu: "500m"

hubUserKeys:
  enabled: true

#--------------------------------------------------------------------------------
# Frontend configuration
#--------------------------------------------------------------------------------
frontend:
  replicas: 1
  ingress:
    path: "/?(.*)"
    servicePort: "8080"
  resources:
    memory: "256Mi"
    cpu: "200m"

#--------------------------------------------------------------------------------
# Postgres
#--------------------------------------------------------------------------------
postgres:
  enabled: true
  pvc:
    storageSize: "100Gi"
    backupVolumeStorageSize: "50Gi"
  image:
    imageUrl: "artifactory.qualytics.io/docker/postgres"
    imageTag: "14"
  resources:
    memory: "12Gi"
    cpu: "2000m"

#--------------------------------------------------------------------------------
# RabbitMQ
#--------------------------------------------------------------------------------
rabbitmq:
  pvc:
    storageSize: "10Gi"
  image:
    imageUrl: "artifactory.qualytics.io/docker/rabbitmq"
    imageTag: "3.12-management"
  resources:
    memory: "1Gi"
    cpu: "1000m"

#--------------------------------------------------------------------------------
# Busybox
#--------------------------------------------------------------------------------
busybox:
  image:
    imageUrl: "artifactory.qualytics.io/docker/busybox"
    imageTag: "latest"