{{- if ( eq .Values.postgres.enabled true ) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  {{- if and ( eq .Values.storageClass.create false ) (ne ( .Values.storageClass.name ) "") }}
  storageClassName: {{ .Values.storageClass.name }}
  {{- else if and ( eq .Values.storageClass.create true ) ( eq .Values.global.platform "aws" ) }}
  storageClassName: aws
  {{- else if and ( eq .Values.storageClass.create true ) ( eq .Values.global.platform "gcp" ) }}
  storageClassName: gcp-fast
  {{- else if and ( eq .Values.storageClass.create true ) ( eq .Values.global.platform "azure" ) }}
  storageClassName: azure-fast
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storageSize }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    service: {{ .Release.Name }}-postgres-service
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - protocol: TCP
      port: 5432
      name: postgres
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      terminationGracePeriodSeconds: 10
      {{- if ( eq .Values.selectors.enabled true ) }}
      nodeSelector:
        appNodes: "true"
      {{- end }}
      {{- if ( eq .Values.tolerations.enabled true ) }}
      tolerations:
        - key: appNodes
          operator: Equal
          value: "true"
          effect: NoSchedule
      {{- end }}
      containers:
      - name: postgres
        args:
          - -c
          - max_connections=10000
          - -c
          - shared_buffers=4GB
          - -c
          - maintenance_work_mem=1GB
          - -c
          - work_mem=512MB
          - -c
          - log_statement=all
          - -c
          - log_destination=stderr
        image: "{{ tpl .Values.postgres.image.imageUrl . }}:{{ .Values.postgres.image.imageTag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: surveillance_hub
          - name: PGDATA
            value: /mnt/data/pgdata
        resources:
          requests:
            {{- with .Values.postgres.resources }}
            memory: {{ .memory }}
            cpu: {{ .cpu }}
            {{- end }}
        volumeMounts:
        - name: postgres-data-pvc
          mountPath: /mnt/data
        - name: pgshm
          mountPath: /dev/shm
      volumes:
        - name: postgres-data-pvc
          persistentVolumeClaim:
            claimName: postgres-data-claim
        - name: pgshm
          emptyDir:
            medium: Memory
            sizeLimit: "4Gi"
{{- end }}