{{- if ( eq .Values.postgres.enabled true ) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  {{- if and ( eq .Values.storageClass.create false ) (ne ( .Values.storageClass.name ) "") }}
  storageClassName: {{ .Values.storageClass.name }}
  {{- else if and ( eq .Values.storageClass.create true ) ( eq .Values.global.platform "aws" ) }}
  storageClassName: aws
  {{- else if and ( eq .Values.storageClass.create true ) ( eq .Values.global.platform "gcp" ) }}
  storageClassName: gcp-fast
  {{- else if and ( eq .Values.storageClass.create true ) ( eq .Values.global.platform "azure" ) }}
  storageClassName: azure-fast
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storageSize }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    service: {{ .Release.Name }}-postgres-service
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - protocol: TCP
      port: 5432
      name: postgres
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 10
      {{- if .Values.appNodeSelector }}
      nodeSelector:
        {{- toYaml .Values.appNodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations.appNodeTolerations }}
      tolerations:
        {{- toYaml .Values.tolerations.appNodeTolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: postgres
        args:
          - -c
          - max_connections=1000  # Adjust based on expected workload
          - -c
          - shared_buffers=4GB  # Set to 25% of total memory, adjust as needed
          - -c
          - maintenance_work_mem=1GB  # Adjust based on your maintenance needs
          - -c
          - work_mem=512MB  # Adjust so that max_connections * work_mem is well below total memory
          - -c
          - effective_cache_size=8GB  # Adjust to about 75% of total memory
          - '-c'
          - jit=off
          - -c
          - log_destination=stderr
        image: "{{ tpl .Values.postgres.image.imageUrl . }}:{{ .Values.postgres.image.imageTag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres
        env:
          - name: POSTGRES_USER
            value: "{{ .Values.secrets.postgres.username }}"
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.secrets.postgres.password }}"
          - name: POSTGRES_DB
            value: "{{ .Values.secrets.postgres.database }}"
          - name: PGDATA
            value: /mnt/data/pgdata
        resources:
          requests:
            {{- with .Values.postgres.resources }}
            memory: {{ .memory }}
            cpu: {{ .cpu }}
            {{- end }}
        volumeMounts:
        - name: postgres-data-pvc
          mountPath: /mnt/data
        - name: pgshm
          mountPath: /dev/shm
      volumes:
        - name: postgres-data-pvc
          persistentVolumeClaim:
            claimName: postgres-data-claim
        - name: pgshm
          emptyDir:
            medium: Memory
            sizeLimit: "4Gi"
{{- end }}