apiVersion: v1
kind: Secret
metadata:
  name: qualytics-creds
type: Opaque
data:
  auth0_audience: {{ .Values.secrets.auth0.auth0_audience | b64enc }}
  auth0_organization: {{ .Values.secrets.auth0.auth0_organization | b64enc }}
  auth0_spa_client_id: {{ .Values.secrets.auth0.auth0_spa_client_id | b64enc }}
  auth0_client_id: {{ .Values.secrets.auth0.auth0_client_id | b64enc }}
  auth0_client_secret: {{ .Values.secrets.auth0.auth0_client_secret | b64enc }}
  auth0_user_client_id: {{ .Values.secrets.auth0.auth0_user_client_id | b64enc }}
  auth0_user_client_secret: {{ .Values.secrets.auth0.auth0_user_client_secret | b64enc }}
  connection_url: {{ .Values.secrets.postgres.connection_url | b64enc }}
  secrets_passphrase: {{ .Values.secrets.postgres.secrets_passphrase | b64enc }}
  smtp_sender_user: {{ .Values.secrets.smtp.smtp_sender_user | b64enc }}
  smtp_sender_password: {{ .Values.secrets.smtp.smtp_sender_password | b64enc }}
  rabbitmq_password: {{ .Values.secrets.rabbitmq.rabbitmq_password | b64enc }}