apiVersion: v1
kind: Secret
metadata:
  name: qualytics-creds
type: Opaque
data:
{{- if ( eq .Values.hub.authType "OIDC" ) }}
  oidc_jwt_signing_secret: {{ .Values.secrets.oidc.oidc_jwt_signing_secret | b64enc }}
  oidc_internal_api_secret: {{ .Values.secrets.oidc.oidc_internal_api_secret | b64enc }}
  oidc_admin_api_secret: {{ .Values.secrets.oidc.oidc_admin_api_secret | b64enc }}
  oidc_scopes: {{ .Values.secrets.oidc.oidc_scopes | b64enc }}
  oidc_authorization_endpoint: {{ .Values.secrets.oidc.oidc_authorization_endpoint | b64enc }}
  oidc_token_endpoint: {{ .Values.secrets.oidc.oidc_token_endpoint | b64enc }}
  oidc_userinfo_endpoint: {{ .Values.secrets.oidc.oidc_userinfo_endpoint | b64enc }}
  oidc_client_id: {{ .Values.secrets.oidc.oidc_client_id | b64enc }}
  oidc_client_secret: {{ .Values.secrets.oidc.oidc_client_secret | b64enc }}
  oidc_user_id_key: {{ .Values.secrets.oidc.oidc_user_id_key | b64enc }}
  oidc_user_email_key: {{ .Values.secrets.oidc.oidc_user_email_key | b64enc }}
  oidc_user_name_key: {{ .Values.secrets.oidc.oidc_user_name_key | b64enc }}
  oidc_user_fname_key: {{ .Values.secrets.oidc.oidc_user_fname_key | b64enc }}
  oidc_user_lname_key: {{ .Values.secrets.oidc.oidc_user_lname_key | b64enc }}
  oidc_user_picture_key: {{ .Values.secrets.oidc.oidc_user_picture_key | b64enc }}
  oidc_user_provider_key: {{ .Values.secrets.oidc.oidc_user_provider_key | b64enc }}
{{- else }}
  auth0_audience: {{ .Values.secrets.auth0.auth0_audience | b64enc }}
  auth0_organization: {{ .Values.secrets.auth0.auth0_organization | b64enc }}
  auth0_spa_client_id: {{ .Values.secrets.auth0.auth0_spa_client_id | b64enc }}
  auth0_client_id: {{ .Values.secrets.auth0.auth0_client_id | b64enc }}
  auth0_client_secret: {{ .Values.secrets.auth0.auth0_client_secret | b64enc }}
  auth0_user_client_id: {{ .Values.secrets.auth0.auth0_user_client_id | b64enc }}
  auth0_user_client_secret: {{ .Values.secrets.auth0.auth0_user_client_secret | b64enc }}
{{- end }}
  connection_url: {{ include "qualytics.postgres.connection_url" . | b64enc }}
  secrets_passphrase: {{ .Values.secrets.postgres.secrets_passphrase | b64enc }}
  smtp_sender_user: {{ .Values.secrets.smtp.smtp_sender_user | b64enc }}
  smtp_sender_password: {{ .Values.secrets.smtp.smtp_sender_password | b64enc }}
  rabbitmq_password: {{ .Values.secrets.rabbitmq.rabbitmq_password | b64enc }}