{{- if ( eq .Values.postgres.enabled true ) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-snapshots-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  {{- if ( eq .Values.global.platform "aws" ) }}
  storageClassName: aws
  {{- else if ( eq .Values.global.platform "gcp" ) }}
  storageClassName: gcp-fast
  {{- else if ( eq .Values.global.platform "azure" ) }}
  storageClassName: azure-fast
  {{- else }}
  storageClassName: local
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.backupVolumeStorageSize }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-snapshotter
  labels:
    role: backups
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            appNodes: "true"
          containers:
          - name: snapshotter
            env:
              - name: URL
                value: postgresql://postgres:postgres@{{ .Release.Name }}-postgres.{{ .Release.Namespace }}.svc.cluster.local:5432/surveillance_hub"
            image: {{ printf "postgres:%s" .Values.postgres.image.version }}
            imagePullPolicy: IfNotPresent
            command:
            - "/bin/sh"
            - "-c"
            - |
              TIMESTAMP=$( date +%Y-%-m-%d.%H%M )
              ARCHIVE="pg_dump.${TIMESTAMP}.sql"
              pg_dump $URL > ./${ARCHIVE}
              gzip -9 ./${ARCHIVE}
              mv ${ARCHIVE}.gz /mnt/data/postgres/${ARCHIVE}.gz
              ls /mnt/data/postgres/
            volumeMounts:
            - name: postgres-snapshots-volume
              mountPath: /mnt/data/postgres
          volumes:
            - name: postgres-snapshots-volume
              persistentVolumeClaim:
                claimName: postgres-snapshots-claim
          restartPolicy: OnFailure
{{- end }}
